import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, average_precision_score
from xgboost import XGBClassifier
import joblib

# 1) Load data generated by generate_synthetic_delirium_data.py
df = pd.read_csv("synthetic_delirium_data.csv")

# 2) Choose feature columns (inputs)
feature_cols = [
    "sound_mean_db",
    "sound_night_db",
    "light_day_lux",
    "light_night_lux",
    "hr_mean",
    "temp_mean",
    "age",
]

X = df[feature_cols]
y = df["delirium_label"].astype(int)

# 3) Train/validation split
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4) Build pipeline: scaler + XGBoost classifier
model = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("clf", XGBClassifier(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="binary:logistic",
            eval_metric="logloss",
            n_jobs=-1,
        )),
    ]
)

# 5) Train
model.fit(X_train, y_train)

# 6) Evaluate
y_val_proba = model.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_val_proba)
ap = average_precision_score(y_val, y_val_proba)

print(f"Validation ROC-AUC: {auc:.3f}")
print(f"Validation PR-AUC:  {ap:.3f}")

# 7) Save model & feature list
joblib.dump(model, "delirium_model.joblib")
joblib.dump(feature_cols, "delirium_features.joblib")
print("Saved delirium_model.joblib and delirium_features.joblib")